[[Qt6QuickTimeline]]
arch = "aarch64"
git-tree-sha1 = "7e925975364328a2c348775f2208bd3070899a7b"
os = "macos"

    [[Qt6QuickTimeline.download]]
    sha256 = "7a1cba55e9608ae03461d7b77366c5b2c2a87198a6044ae368a9ced9bac836d4"
    url = "https://github.com/JuliaBinaryWrappers/Qt6QuickTimeline_jll.jl/releases/download/Qt6QuickTimeline-v6.10.2+0/Qt6QuickTimeline.v6.10.2.aarch64-apple-darwin.tar.gz"
[[Qt6QuickTimeline]]
arch = "x86_64"
git-tree-sha1 = "358e0b37fd970ff252cdaa65bf02aa9d92d3581b"
os = "macos"

    [[Qt6QuickTimeline.download]]
    sha256 = "75fb1daf976b7850649c90cd8e3dbd4cb3a404517fde26b89bb330ca7b8adacd"
    url = "https://github.com/JuliaBinaryWrappers/Qt6QuickTimeline_jll.jl/releases/download/Qt6QuickTimeline-v6.10.2+0/Qt6QuickTimeline.v6.10.2.x86_64-apple-darwin.tar.gz"
[[Qt6QuickTimeline]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7896344f59fc2f89e3edfbc361d38f1e97c3e6d0"
os = "windows"

    [[Qt6QuickTimeline.download]]
    sha256 = "b0d2e7557145726d7490b466cf3b20c908f13e865f31c15dbcb7ea6b4d593d16"
    url = "https://github.com/JuliaBinaryWrappers/Qt6QuickTimeline_jll.jl/releases/download/Qt6QuickTimeline-v6.10.2+0/Qt6QuickTimeline.v6.10.2.i686-w64-mingw32-cxx11.tar.gz"
[[Qt6QuickTimeline]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2d2b7b5b101e759faa62bc57d2d63d0fb6fbcd33"
os = "windows"

    [[Qt6QuickTimeline.download]]
    sha256 = "0cec38d628a1e01ebba5d79f23d2d4c5200810c4613c1ca94aaf808aac5215e1"
    url = "https://github.com/JuliaBinaryWrappers/Qt6QuickTimeline_jll.jl/releases/download/Qt6QuickTimeline-v6.10.2+0/Qt6QuickTimeline.v6.10.2.x86_64-w64-mingw32-cxx11.tar.gz"
[[Qt6QuickTimeline]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "93be21b72441189d8133a4ee634300bc8e5394b6"
libc = "glibc"
os = "linux"

    [[Qt6QuickTimeline.download]]
    sha256 = "22dcc16f8a448f38fb88beb63ec237dcecc8acfe7a7e190a6dcef110455753d9"
    url = "https://github.com/JuliaBinaryWrappers/Qt6QuickTimeline_jll.jl/releases/download/Qt6QuickTimeline-v6.10.2+0/Qt6QuickTimeline.v6.10.2.aarch64-linux-gnu-cxx11.tar.gz"
[[Qt6QuickTimeline]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7f2b4b35075215e8d03ba3cd97083548bcd9809c"
libc = "musl"
os = "linux"

    [[Qt6QuickTimeline.download]]
    sha256 = "490706c0f25cf0ed6c2af4e0ec6930f620a5bf28dfb9e28d9c93dd112f7189b2"
    url = "https://github.com/JuliaBinaryWrappers/Qt6QuickTimeline_jll.jl/releases/download/Qt6QuickTimeline-v6.10.2+0/Qt6QuickTimeline.v6.10.2.aarch64-linux-musl-cxx11.tar.gz"
[[Qt6QuickTimeline]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "08d37aa1d40a324ea56be93ec5b078814a452b6f"
libc = "glibc"
os = "linux"

    [[Qt6QuickTimeline.download]]
    sha256 = "1650aefbb5a81f69f2967bccf189770ddb07837a60b91633cb6a88db58845729"
    url = "https://github.com/JuliaBinaryWrappers/Qt6QuickTimeline_jll.jl/releases/download/Qt6QuickTimeline-v6.10.2+0/Qt6QuickTimeline.v6.10.2.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Qt6QuickTimeline]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "52381e23193e8f8be9f88b331a35d3b26e4cb4f6"
libc = "musl"
os = "linux"

    [[Qt6QuickTimeline.download]]
    sha256 = "9963fd420794249ca7599c86c34b8f4d8e4bcc48ff95ff90cb608c9b53678566"
    url = "https://github.com/JuliaBinaryWrappers/Qt6QuickTimeline_jll.jl/releases/download/Qt6QuickTimeline-v6.10.2+0/Qt6QuickTimeline.v6.10.2.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Qt6QuickTimeline]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f38f67a9eb1a62950d4249db370907ff7796c295"
libc = "glibc"
os = "linux"

    [[Qt6QuickTimeline.download]]
    sha256 = "48d8286ae66d400b79c16c273abac512ac88b2942a52cf67e12a8f88a480cdc3"
    url = "https://github.com/JuliaBinaryWrappers/Qt6QuickTimeline_jll.jl/releases/download/Qt6QuickTimeline-v6.10.2+0/Qt6QuickTimeline.v6.10.2.i686-linux-gnu-cxx11.tar.gz"
[[Qt6QuickTimeline]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9420f02f46b443a764d83a61d1ee4fc19705812a"
libc = "musl"
os = "linux"

    [[Qt6QuickTimeline.download]]
    sha256 = "c73ee4686314c5a2569c5d55218b3dad679d0843d9098c527527a94cdf880edb"
    url = "https://github.com/JuliaBinaryWrappers/Qt6QuickTimeline_jll.jl/releases/download/Qt6QuickTimeline-v6.10.2+0/Qt6QuickTimeline.v6.10.2.i686-linux-musl-cxx11.tar.gz"
[[Qt6QuickTimeline]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "203bd3944dc99f84fc5cbcd8f3eb137b41a1770c"
libc = "glibc"
os = "linux"

    [[Qt6QuickTimeline.download]]
    sha256 = "7f8fc121d541986afeed0a3695fb038f728d765911fddf545a8fd824c5cece67"
    url = "https://github.com/JuliaBinaryWrappers/Qt6QuickTimeline_jll.jl/releases/download/Qt6QuickTimeline-v6.10.2+0/Qt6QuickTimeline.v6.10.2.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Qt6QuickTimeline]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "13cc4eb3f7a887f3d23bd0e064da5a81f3c81214"
libc = "glibc"
os = "linux"

    [[Qt6QuickTimeline.download]]
    sha256 = "3ff6b8b713c78ca8271fbbb6d7dc31bc441605061b2e356de826e3120ef663b1"
    url = "https://github.com/JuliaBinaryWrappers/Qt6QuickTimeline_jll.jl/releases/download/Qt6QuickTimeline-v6.10.2+0/Qt6QuickTimeline.v6.10.2.x86_64-linux-gnu-cxx11.tar.gz"
[[Qt6QuickTimeline]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a2c8492636db7735a7a7d2095e4e45eb4d8744b9"
libc = "musl"
os = "linux"

    [[Qt6QuickTimeline.download]]
    sha256 = "d87a4b1391f099c9e2ec486dd9f39a02152d0b5d1a6744884770e681d3b804f4"
    url = "https://github.com/JuliaBinaryWrappers/Qt6QuickTimeline_jll.jl/releases/download/Qt6QuickTimeline-v6.10.2+0/Qt6QuickTimeline.v6.10.2.x86_64-linux-musl-cxx11.tar.gz"
[[Qt6QuickTimeline]]
arch = "x86_64"
git-tree-sha1 = "ae2aa65774e7c3847113d63c33185490ac8e2a8d"
os = "freebsd"

    [[Qt6QuickTimeline.download]]
    sha256 = "05cd6fdb9d3904848df5bbf0a26d767fbb0e2f5658e267d6803498ec1ed5e8df"
    url = "https://github.com/JuliaBinaryWrappers/Qt6QuickTimeline_jll.jl/releases/download/Qt6QuickTimeline-v6.10.2+0/Qt6QuickTimeline.v6.10.2.x86_64-unknown-freebsd.tar.gz"
